name: CI

on:
  # reusing workflow trigger
  workflow_call:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'World'
        type: string

jobs:
  ci:
    runs-on: [ self-hosted, es-demos ]

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - run: echo "Hello ${{ inputs.name }}"
