name: Lint & CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  lint:
    runs-on: [ self-hosted, es-demos ]
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - run: echo "Linting..."

  ci:
    needs: [lint]
    uses: es-demos/.github/.github/workflows/ci.yml@main
