name: Check privileged option

on:
  pull_request:
    paths: '.github/workflows/*'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-privileged:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/workflows
          
      - name: Execute check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # Limit search directory
          directory=".github/workflows"
          
          if [ ! -d "$directory" ]; then
            echo "Directory $directory does not exist."
            exit 0
          fi

          # Search for YAML or YML files
          yaml_files=$(find "$directory" -type f \( -iname "*.yaml" -o -iname "*.yml" \))
          
          # Check if there are YAML or YML files
          if [ -z "$yaml_files" ]; then
              echo "No YAML or YML files found in $directory."
              exit 0
          fi
          
          # Search for the pattern in YAML or YML files
          matches=$(grep -r -E 'options:(?:.*?--privileged\b)' $yaml_files 2>/dev/null)


          # Check the exit code of grep
          if [ -n "$matches" ]; then
              # Pattern matched
              # Set up your GitHub API details
          
              # Create a comment to add to the pull request
              COMMENT="🛑 The pull request contains workflows files using `--privileged` option which is not permitted."

              # Post the comment to the pull request using the GitHub API
              curl -X POST \
              -H "Authorization: token ${GH_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"body\": \"$COMMENT\"}" \
              "https://api.github.com/repos/${OWNER_REPO}/issues/${PR_NUMBER}/comments"

          else
              # Pattern not matched
              echo "No matches found."
              exit 0
          fi
