name: Check privileged option

on:
  pull_request:
    paths: '.github/workflows/*'
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-privileged:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/workflows
          
      - name: Execute check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # Search for the pattern in YAML or YML files
          grep -c -r -E 'options:(?:.*?--privileged\b)' .github/workflows/*.{yml,yaml} 2>/dev/null
          matches=$(grep -r -E 'options:(?:.*?--privileged\b)' .github/workflows/*.{yml,yaml} 2>/dev/null || true)

          # Check the exit code of grep
          if [ -n "$matches" ]; then
              # Pattern matched
          
              # Create a comment to add to the pull request
              COMMENT="🛑 The pull request contains workflows files using `--privileged` option which is not permitted."

              # Post the comment to the pull request using the GitHub API
              curl -X POST \
              -H "Authorization: token ${GH_TOKEN}" \
              -H "Content-Type: application/json" \
              -d "{\"body\": \"$COMMENT\"}" \
              "https://api.github.com/repos/${OWNER_REPO}/issues/${PR_NUMBER}/comments"
              exit 1
          else
              # Pattern not matched
              echo "No matches found."
              exit 0
          fi
